Introduction. course work. nightmare
mqithelp/Introduction pull request #12
Opened 2024-07-10 12:53 UTC by mqithelp

2024-07-10 14:47 UTC, OlgaLugacheva requested changes

2024-07-10 14:47 UTC, OlgaLugacheva commented on src/Employee.java
> +    private static int[] personsDepartment = new int[6];
немного сомнительно тут иметь поле типа массива, ведь сотрудник должен принадлежать всего к одному отделу
это стоит поправить

2024-07-10 14:47 UTC, OlgaLugacheva commented on src/Employee.java
> +//        return id == employee.id && department == employee.department && salary == employee.salary && Objects.equals(name, employee.name) && Objects.equals(surname, employee.surname) && Objects.equ
закомментировпнный код нужно убрать

2024-07-11 05:09 UTC, pavelilyukevichsky commented on src/Employee.java
> +    public static int countId = 0;
надо поставить private вместо public и лучше назвать counter и =0 не надо делать т.к. и так по умолчанию будет 0
`private static int counter;`

2024-07-11 05:10 UTC, pavelilyukevichsky commented on src/Employee.java
> +    public static int getPersonsDepartment(int id) {
все static удаляем из методов. это не надо тут.

2024-07-11 05:11 UTC, pavelilyukevichsky commented on src/Employee.java
> +    public String getFullName() {
перенести весь метод на 70 строку. это логика класса она должна идти перед иквалс

2024-07-11 05:21 UTC, pavelilyukevichsky commented on src/Employee.java
> +        if (department <= 1 || department >= 6) {
`department < 1`
если 1 то и зачем заходить в иф?
лучше тут записать
`if (department < 1 || department >5) {`

2024-07-11 05:22 UTC, pavelilyukevichsky commented on src/Employee.java
> +        this.department = department;
так же тут нету этой проверки `if (department < 1 || department >5) {` и я могу установить -1 отдел

2024-07-11 05:23 UTC, pavelilyukevichsky commented on src/Employee.java
> +    }
с 13 по 23 строку - не нужные методы. зачем это?

2024-07-11 05:25 UTC, pavelilyukevichsky commented on src/Employee.java
> +    public Employee(String surname, String name, String patronymic, int department, int salary) {
конструктор надо переместить на 12 строку т.е после объявления переменных

2024-07-11 05:32 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +        fullArray(this.employee);
лучше назвать метод init

2024-07-11 05:33 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +    private final int[] statusArrayPersons = new int[10];
5 и 6 строки не нужны

2024-07-11 05:36 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +        return getTotalSalaryMonth(department) / Employee.getPersonsDepartment(department);
тут надо написать логику. 
бежим по сотрудникам если department == департаменту сотрудника то  суммируем в переменную сумм и увеличиваем счетчик. а потом сумм / ну счетчик.

2024-07-11 05:39 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +        return employee[indexMinSalary].toString();
во всех методах .toString(); вызывается. лучше возвращать объект Employee а там где надо уже вызвать .toString(); или то что нужно. Иначе ваш метод придется править если придет условие возвращать имя и фамилию

2024-07-11 05:40 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +            if (statusArrayPersons[i] == 1) {
статусы тут не нужны. поэтому можно удалить эту логику.

2024-07-11 12:22 UTC, mqithelp commented on src/Employee.java
> +    public static int getPersonsDepartment(int id) {
т.к. массив personsDepartment я сделал static и перенес в класс EmployeeBook то этот метод getPersonsDepartment() не нужен. 
этот массив хранит информацию о количестве сотрудников в каждом отделе. Как раз для того чтобы при подсчете средней зп по отделу лишний раз не пробегать по циклу выискивая нужных сотрудников.

2024-07-11 12:31 UTC, mqithelp commented on src/Employee.java
> +        this.department = department;
:-) пропустил. Исправил.

2024-07-11 12:34 UTC, mqithelp commented on src/Employee.java
> +        if (department <= 1 || department >= 6) {
подправил )

2024-07-11 12:35 UTC, mqithelp commented on src/Employee.java
> +    }
удалил

2024-07-11 12:41 UTC, mqithelp commented on src/EmployeeBook.java
> +    private final int[] statusArrayPersons = new int[10];
statusArrayPersons -- хранит состояние занята ячейка (1) или свободна (0). Используется с методом deletePerson()

2024-07-11 12:57 UTC, mqithelp commented on src/EmployeeBook.java
> +            if (statusArrayPersons[i] == 1) {
статус нужен для определения ячейки которая освобождается. Чтобы потом при добавлении знать куда вставлять запись. 
Я помню -- в уроке использовали метод с копированием массива. Я вот избрал иной путь ) мне он показался проще ))) мне кажется что если бы сотрудников было бы много, то копирование массива отняло бы больше ресурсов.

2024-07-11 13:01 UTC, mqithelp commented on src/EmployeeBook.java
> +        return getTotalSalaryMonth(department) / Employee.getPersonsDepartment(department);
как раз для того чтобы эту логику тут не писать -- был введен массив personDepartment[]. Который и хранит количество сотрудников в каждом отделе.

2024-07-11 13:28 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +            if (statusArrayPersons[i] == 1) {
теперь понятно.
можно проще сделать. написать метод который ищет свободную ячейку. фактически вы это и делаете со статусами. но вы используете доп. массив - это усложняет логику.
```
private int findFreeIndex() {
        for (int i = 0; i < employees.length; i++) {
            if (employees[i] == null) {
                return i;
            }
        }
        return -1;
    }
```

2024-07-11 13:31 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +        return getTotalSalaryMonth(department) / Employee.getPersonsDepartment(department);
не нужно так делать. это сложно поддерживать и расширять логику(логика должна быть простая, чем проще код тем проще его поддерживать). проще завести переменную и не создавать массив для хранения количества сотрудников отделов.

2024-07-11 13:31 UTC, pavelilyukevichsky commented on src/Employee.java
> +    public static int getPersonsDepartment(int id) {
ок

2024-07-11 13:33 UTC, pavelilyukevichsky commented on src/EmployeeBook.java
> +    private final int[] statusArrayPersons = new int[10];
очень трудно было понять что и зачем нужно. задача простая надо реализовывать по простому. Не надо делать доп. массивы. Тут у нас 10 сотрудников а если будет 100 000? сразу память надо на 2 увеличивать из за второго массива.

2024-07-12 13:38 UTC, merged